version: "3.9"

services:
  app:
    image: neosmemo/memos:latest
    restart: always
    volumes:
      - ${BASE_VOLUME}/data:/var/opt/memos
    expose:
      - 5230
    networks:
      - nginx
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5230"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: ${LIMIT_CPU_APP:-0.5}
          memory: ${LIMIT_RAM_APP:-128M}
        reservations:
          cpus: 0.1
          memory: 10M

networks:
  nginx:
    external: true